# Site settings
title: Firas H. Wehbe, MD, PhD
email: firas.wehbe@northwestern.edu
description: > # this means to ignore newlines until "baseurl:"
  Biomedical Informatics professional. Focus on research and infrastructure in
  Clinical Research Informatics and Cancer Informatics (including precision
  oncology). Faculty at Northwestern University Feinberg School of Medicine.
  Opinions are my own.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://firaswehbe.github.io" # the base hostname & protocol for your site
twitter_username: fhwehbe
github_username: firaswehbe
timezone: America/Chicago

# Build settings
markdown: kramdown
